# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('data_time', models.DateTimeField()),
                ('title_article', models.CharField(max_length=100)),
                ('article_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Add text_comments')),
                ('comments_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.Article')),
            ],
        ),
    ]
