# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Add text_comments')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='title_article',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.Article'),
        ),
    ]
